
package com.tvelykyy.afeeder.webservice.soap.client.wsimported;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ActivityWebServiceEndpointService", targetNamespace = "http://soap.webservice.afeeder.tvelykyy.com/", wsdlLocation = "http://localhost:9999/?wsdl")
public class ActivityWebServiceEndpointService
    extends Service
{

    private final static URL ACTIVITYWEBSERVICEENDPOINTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.tvelykyy.afeeder.webservice.soap.client.wsimported.ActivityWebServiceEndpointService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.tvelykyy.afeeder.webservice.soap.client.wsimported.ActivityWebServiceEndpointService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9999/?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9999/?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ACTIVITYWEBSERVICEENDPOINTSERVICE_WSDL_LOCATION = url;
    }

    public ActivityWebServiceEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityWebServiceEndpointService() {
        super(ACTIVITYWEBSERVICEENDPOINTSERVICE_WSDL_LOCATION, new QName("http://soap.webservice.afeeder.tvelykyy.com/", "ActivityWebServiceEndpointService"));
    }

    /**
     * 
     * @return
     *     returns ActivityWebService
     */
    @WebEndpoint(name = "ActivityWebServicePort")
    public ActivityWebService getActivityWebServicePort() {
        return super.getPort(new QName("http://soap.webservice.afeeder.tvelykyy.com/", "ActivityWebServicePort"), ActivityWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivityWebService
     */
    @WebEndpoint(name = "ActivityWebServicePort")
    public ActivityWebService getActivityWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.webservice.afeeder.tvelykyy.com/", "ActivityWebServicePort"), ActivityWebService.class, features);
    }

}
